TITLE = "Snake"
ROW_COUNT = 20
COLUMN_COUNT = 20
WIDTH = 30
HEIGHT = 30
MARGIN = 5

SCREEN_WIDTH = (WIDTH + MARGIN) * COLUMN_COUNT + MARGIN
SCREEN_HEIGHT = (HEIGHT + MARGIN) * ROW_COUNT + MARGIN

GAME_VIEW_UPDATE_RATE = 20 / 60
