[tool.black]
line-length = 120
target-version = ['py313']
include = '\.pyi?$'
extend-exclude = '''
/(
  # The following are specific to Black, you probably don't want those.
  | venv/
  | .idea/
)/'''

[tool.isort]
multi_line_output = 3
line_length = 120
include_trailing_comma = true

[tool.poetry]
name = "snake_arcade"
version = "0.1.0"
description = "Template description"
authors = ["Ross <rostikvunarchuk@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.13"
arcade = "^3.2"

[tool.poetry.group.dev.dependencies]
black = "^24.8.0"
isort = "^5.13.2"
pytest = "^8.3.2"
pylint = "^3.2.7"
bandit = "^1.7.9"
xenon = "^0.9.1"
mypy = "^1.11.2"
toml = "^0.10.2"
pre-commit = "^3.8.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pylint.master]
fail-under = 9.5

[tool.pylint]
max-line-length = 120
disable=["C0114", "C0116", "R0903"]

[tool.bandit]
tests = ["B201", "B301"]
skips = ["B101", "B601"]

[tool.mypy]
disallow_untyped_defs = true
warn_return_any = true
warn_unused_configs = true
no_implicit_optional = true
check_untyped_defs = true
show_error_codes = true
